from .imgscore import BaseImageClassificationScore, ImageClassificationAugmentConfidence
from .latentscore import BaseLatentScore, LatentClassificationAugmentConfidence
from .funtional import cross_image_augment_scores, specific_image_augment_scores